FROM python:3.10.1

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

# Only update packages
RUN apt-get update

# Set working directory
WORKDIR /new

# copy requirements files
COPY ./requirements.txt /new2/requirements.txt

# install requirements
RUN pip install -r requirements.txt

# Copy codebase
COPY . /new/

# create new user
RUN adduser --disabled-password --gecos '' jerry

# Set user as the owner of directory
RUN chown -R jerry:jerry /new

# Set user to be jerry
USER jerry